version: "3"
services:
  remindandinform:
    # TODO add correct name matching nexus repository also add build number parameter as suffix
    image: 'ms-remindandinform:latest'
    restart: always
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    ports:
        - '9081:8080'